### ISSUE TITLE
Can't rerender

### ISSUE THREAD

**Issue by kmod** [conda-forge/ephem-feedstock#27]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When I run `conda-smithy rerender`, I get the following:
```
$ conda-smithy rerender
INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2022.03.28.19.38.17
INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmpv242m95q
INFO:conda_smithy.configure_feedstock:pypy37-windows.yaml from feedstock is ignored and upstream version is used
INFO:conda_smithy.configure_feedstock:pypy37.yaml from feedstock is ignored and upstream version is used
INFO:conda_smithy.configure_feedstock:python310.yaml from feedstock is ignored and upstream version is used
Traceback (most recent call last):
  File "/home/kmod/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/cli.py", line 681, in main
    args.subcommand_func(args)
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/cli.py", line 486, in __call__
    self._call(args, tmpdir)
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/cli.py", line 491, in _call
    configure_feedstock.main(
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 2258, in main
    render_circle(env, config, forge_dir, return_metadata=True)
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 1057, in render_circle
    ) = _get_platforms_of_provider("circle", forge_config)
  File "/home/kmod/miniconda3/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 998, in _get_platforms_of_provider
    build_platform, build_arch = build_platform_arch.split("_")
ValueError: not enough values to unpack (expected 2, got 1)
```

The value of build_platform is "default". It looks like this comes from conda-forge.yml which has this string there; I don't know enough about conda-smithy/conda-forge to know if this is an ephem issue or conda-smithy issue, but it seems like an issue in at least one of them?

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by kmod** [comment]
thanks!

**Comment by ocefpaf** [comment]
Thanks for reporting it. I would never find it if you did not bring it to our attention. This is one of the things we trust the infrastructure but the infrastructure was failing silently.
